version: "3"


services:
  db:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "9900psql"
  backend:
    restart: always
    build: ./backend
    environment:
      - WEB_DOMAIN=https://0.0.0.0:443
      - DJANGO_DEBUG=true
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/backend
      - ./frontend/build:/backend/public
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:9000
  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./MyCertificate.crt:/MyCertificate.crt
      - ./MyKey.key:/MyKey.key
      - ./frontend/build:/usr/share/nginx/html/public
      - ./backend/media:/usr/share/nginx/html/media
    depends_on:
      - backend
    ports:
      - "443:443"
    
  